services:
  - type: web
    name: catchall-temp-inbox
    runtime: python
    repo: https://github.com/sleep2k0965388977-png/catchall-temp-inbox
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
    plan: free
    autoDeploy: true
